kind = "web"
previewPath = "/"
title = "Villah Portfolio"
version = "1.0.0"
id = "artifacts/villah-portfolio"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25048

[services.development]
run = "pnpm --filter @workspace/villah-portfolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/villah-portfolio", "run", "build" ]
publicDir = "artifacts/villah-portfolio/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25048"
BASE_PATH = "/"
